### ISSUE TITLE
Compression of cluster type backups

### ISSUE THREAD

**Issue by saz** [rafaelma/pgbackman#25]
First of all, thanks for pgbackman. It looks very promising.

It would be great, if it's possible to compress cluster type backups (e.g piping them to gzip).

Or am I missing something and this is already possible?

**Comment by rafaelma** [comment]
On 10/30/2015 10:59 AM, Steffen Zieger wrote:
> First of all, thanks for pgbackman. It looks very promising.
> 
> It would be great, if it's possible to compress cluster type backups
> (e.g piping them to gzip).
> 
> Or am I missing something and this is already possible?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rafaelma/pgbackman/issues/25>.
> 

Hello

Thank you for your feedback :-)

You are not missing anything.

PgBackMan use "directory" format with pg_dump (Backup type: data,
full,schema) and this format compress all backups created. But, you are
right, we don't compress backups of type 'cluster' (created with
pg_dumpall).

This is not difficult to implement as you say, I will do it for the next
version.

-- 
Rafael Martinez Guerrero
Center for Information Technology
University of Oslo, Norway

PGP Public Key: http://folk.uio.no/rafael/

**Comment by saz** [comment]
Glad to hear! Thank you!
